Repository dolbwa/dolbwa_frontend, pull requests merged in 2023-12, with the labels that each got.

#2 chore: 정적 빌드 설정 및 명령어 추가
  next.config.js
  package.json
Labels: settings

#4 feat: 인증 코드 API 호출 기능 추가
  .env
  src/api/auth.ts
  src/components/PageAuthGuard.tsx
  src/components/SignInForm.tsx
  src/hooks/fetchInterceptor.ts
  src/store/userState.ts
  src/utils/fetchInterceptor.ts
Labels: feat, settings

#5 fix: rewrite 옵션 제거
  next.config.js
Labels: bug, bugfix

#6 remove .env파일 제거
  .env
Labels: settings
